from geographica/urbo_core_www:latest

COPY deploy/www/Config.prod.js /usr/src/app/src/Config.js
COPY deploy/www/s3_website.prod.yml /usr/src/app/s3_website.yml
COPY aq_cons/www /usr/src/app/src/verticals/aq_cons
