FROM aquasig_base:latest

# Variables de entorno para la conexión a Urbo.
ENV URL 'jdbc:postgresql://XXXX:XXXX/XXXX'
ENV USERNAME 'XXXX'
ENV PASSWORD 'XXXX'
ENV SCHEMA 'XXXX'

RUN env > /root/environmentVariables.txt

# Cargamos los ficheros del proyecto
COPY ./project/ /usr/local/app/project/
COPY ./src/ /usr/local/app/src/
COPY build.sbt /usr/local/app/

# Compilamos con dependencias
RUN cd /usr/local/app/ && sbt assembly

# Script con la instrucción de lanzamiento del programa
COPY ./entrypoint.sh /
RUN chmod +x /entrypoint.sh

# Creamos fichero de log
RUN touch /var/log/fase2-cron.log && chmod +rw /var/log/fase2-cron.log

# Cargamos el cron
ADD fase2-cron /etc/cron.d/fase2-cron
RUN chmod +x /etc/cron.d/fase2-cron && crontab -u root /etc/cron.d/fase2-cron

CMD cron && tail -f /var/log/fase2-cron.log
